security:

    encoders:
        Dexer\Bundle\UserBundle\Entity\User:
             algorithm:        sha1
             encode_as_base64: false
             iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    
    providers:
        main:
            entity: { class: Dexer\Bundle\UserBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/(login$|register|resetting)  # Les adresses de ces pages sont login, register et resetting
            anonymous: true

        main:
            pattern:    ^/
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path:   logout
                target: /
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

        admin_area:
            pattern:   ^/admin
            http_basic: ~            
            

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
